plugins:
    - react
    - react-hooks

extends:
    - '../.eslintrc.yml'
    - plugin:react/recommended
    - plugin:react-hooks/recommended

rules:
    react/react-in-jsx-scope: off
    react/prop-types: 0
    indent:
        - error
        - 4

settings:
    react:
        version: 'detect'
