version: "3.9"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
  client:
    build: 
      context: './frontend'
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  server:
    build: 
      context: './backend'
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - postgres

volumes:
  data:
