version: "3.9"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
  client:
    build: 
      context: './frontend'
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  server:
    build: 
      context: './backend'
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - postgres
  pg-admin:
    image: dpage/pgadmin4:6
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - 5050:5050

volumes:
  data:
